# Generated by Django 3.2.12 on 2022-08-19 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_category',
            field=models.CharField(choices=[('ROMANCE', 'romance'), ('FICTION', 'fiction'), ('DRAMA', 'drama'), ('POLITICS', 'politics'), ('CRIME', 'crime')], default='ROMANCE', max_length=50),
        ),
    ]
